### PR TITLE
Use an atom instead of a var for text dictionary.

### PR DESCRIPTION
**Pull request by CharlesHD**
Purpose : modification of the text source dictionary is easier with an atom and works both in Clojure and Clojurescript. It can change default text used internally. 

The change is pretty light. 

I also add a `set-dictionary!` function for providing a clear way of changing the dictionary. So if you want to swap atom for another construct it will be transparent for the API user.

### CODE REVIEW

**Comment by facundoolano** [comment]
did you tied it to see if it works with a game (perhaps the example-game)? 

I worry about some translated strings that are used in maps and things like that, I remember at some point I had issues with setting the dictionary after the advenjure namespaces were initialized

**Comment by CharlesHD** [comment]
I'll try on mine. I'll add some tests if you want using your different tense dictionaries.

**Comment by facundoolano** [comment]
Tests are not necessary I think, just want to make sure it works before merging

**Comment by CharlesHD** [comment]
I tried both on jvm and javascript. Phrases I changed were indeed replaced in both cases. 
I dunno if the example game is fully compatible with the current state of the lib (it uses version "0.6.3").

**Comment by facundoolano** [comment]
the `advenjure-v1` of the example game works with the current master of advenjure

**Comment by CharlesHD** [comment]
I made a fork of [the example game](https://github.com/CharlesHD/advenjure-example) and set a branch dictionary-test where I set the dictionary to the present tense one. It works as expected on my manual checks. 

You can clone my advenjure repo, install it to your local maven repo then clone the advenjure-example one to test it by yourself.

**Comment by CharlesHD** [comment]
Oh. I got a case where it does not work as expected. The en_present dictionary does not cover the article case for "a" and "an" that the en_past dictionary covers. I think it's more an error in the en_present dictionary than anything else.

**Comment by facundoolano** [comment]
I just tested using the spanish translations, and this suffers the case I mentioned earlier. The english present that you tested is ok because it doens't redefine the verbs, but in spanish this happens:

```
@Bedroom [P:0 | M:1] > mirar alrededor
No sabía cómo hacer eso.

@Bedroom [P:0 | M:1] > look around
A smelling bedroom. There was an unmade bed near the corner and a door to the
north. A thin ladder leaded up. Just by the table, a trash bin. The floor was
scratched near the bed.
```

The reason is that the verbs are defined statically in the code so by the time the atom is assigned they are already defined using the default language. ([here for example](https://github.com/facundoolano/advenjure/blob/master/src/advenjure/verbs.cljc#L412))

The original gettext read the dictionary from a configuration file so it worked statically; we'll need to think this one a bit more to make it work.

I think for the purposes of your game you'll be better off by forking and changing the default dictionary to point to the namespace with your translations.

**Comment by facundoolano** [comment]
Another option to explore is to use [closure-defines](https://cljs.github.io/api/compiler-options/closure-defines) to point a translation dictionary in project.clj

That would work for clojurescript (which is the priority), and maybe we could bring back [carica](https://github.com/sonian/carica) for clojure.

**Comment by CharlesHD** [comment]
Oh I see ! indeed verbs are statically constructed. 

- A simple workaround is to wrap that construction in a function (and do the same thing for the default verb-map construction) so it will be dynamically construct at the game creation and will fetch the translations. I don't think it will add that much start up time for the game right ?
- Another workaround is to define the dictionary staticaly just like gettext and bind it at namespace evaluation. 

Isn't there an issue on how the dictionary is defined and how your gettext function work ?
If I look [here](https://github.com/facundoolano/advenjure/blob/f62168c2e2249e8c46040ddd235c70bdcb00f90d/src/advenjure/text/es_past.cljc#L58) I see that the es dictionary key for "look around" is in a regex form : `"^look around$"`. 

But If I look at the [gettext function](https://github.com/facundoolano/advenjure/blob/f62168c2e2249e8c46040ddd235c70bdcb00f90d/src/advenjure/gettext/core.cljc#L12)  I see there is no mecanism to match that regex. So when a call to `(gettext "look around")` is made my guess is it won't hit the right key in the dictionary map.  I tested it on the REPL and indeed it won't: 

```
example.game> (advenjure.gettext.core/gettext "look around")
"look around"
example.game> (advenjure.gettext.core/gettext "^look around$")
"^mirar alrededor$"
```

Here I see two way of doing it: 

- On one hand we could redefine the es dictionary to match the way verbs command are named (I think it's the easy solution). 
- On the other hand we could redefine `gettext` to match more complex construct like the ones in the es dictionary.

**Comment by CharlesHD** [comment]
I just wrote two commits to my branch. The first one explore the dynamically construct verbs and verb-map. The second rewrite the espagnol dictionary for matching the way you refer to text in the verbs file. 
I also add a commit to my [advenjure example fork](https://github.com/CharlesHD/advenjure-example) that test the es dict. Es verbs are indeed available. The dictionary isn't full yet, and some verbs aren't dynamically defined either (tike take). I'll fix that this afternoon.

**Comment by CharlesHD** [comment]
OK. After some reflexion I just hit the conclusion that using static dictionary would be far more easier. (Sorry for experimenting, you have a far larger overview of your project than I do)

I just saw your original gettext library and I think it's pretty neat and that we should make it work for clojurescript. I guess the missing point was carica not portable to clojurescript ? I suggest we use [cprop](https://github.com/tolitius/cprop) that is a both java / javascript configuration reader.

**Comment by CharlesHD** [comment]
Okay, was wondering how people are doing to compile clojurescript code using configurations maps. 

The trick is to bind the configuration at compile time using macro and it work as is in clojurescript. An exemple is given in [this discussion](https://groups.google.com/forum/#!topic/clojurescript/YV-051DmdFE). 

If we just wrap your carica calls in a macro I think gettext should be portable as is.

**Comment by CharlesHD** [comment]
Yes it's working too. I just supposed you would like having your previous workflow working.

I made [another fork here](https://github.com/facundoolano/advenjure/compare/master...CharlesHD:static-dict) where I show how it could be done. This solution works for both clojure and clojurescript and should be use in [gettext](https://github.com/facundoolano/clojure-gettext). The key is to integrate the dictionary during macro expand time.

**Comment by facundoolano** [comment]
Nice, that looks good. You can make A PR with that change and let me test it over the weekend.

**Comment by facundoolano** [comment]
closing this in favor of #43

**Pull request closed without merging**
